#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "http.h"
#include "fio.h"

// Fungsi untuk menghasilkan halaman HTML
static void on_request(http_s *request, http_s *response) {
    const char *html = 
        "<!DOCTYPE html>"
        "<html lang='id'>"
        "<head>"
        "    <meta charset='UTF-8'>"
        "    <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        "    <title>Operating Systems by Domain</title>"
        "    <style>"
        "        * { margin: 0; padding: 0; box-sizing: border-box; }"
        "        body {"
        "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;"
        "            background: linear-gradient(135deg, #0f0c29, #302b63, #24243e);"
        "            min-height: 100vh;"
        "            display: flex;"
        "            justify-content: center;"
        "            align-items: center;"
        "            padding: 20px;"
        "        }"
        "        .container {"
        "            background: rgba(255, 255, 255, 0.95);"
        "            border-radius: 20px;"
        "            padding: 40px;"
        "            max-width: 900px;"
        "            width: 100%;"
        "            box-shadow: 0 20px 60px rgba(0,0,0,0.7);"
        "        }"
        "        h1 {"
        "            text-align: center;"
        "            font-size: 2.2em;"
        "            color: #1a1a2e;"
        "            margin-bottom: 30px;"
        "            border-bottom: 4px solid #302b63;"
        "            padding-bottom: 15px;"
        "            letter-spacing: 1px;"
        "        }"
        "        .domain-card {"
        "            display: flex;"
        "            justify-content: space-between;"
        "            align-items: center;"
        "            padding: 16px 20px;"
        "            margin: 10px 0;"
        "            background: #f8f9fc;"
        "            border-radius: 12px;"
        "            border-left: 6px solid #302b63;"
        "            transition: all 0.3s ease;"
        "        }"
        "        .domain-card:hover {"
        "            transform: translateX(8px);"
        "            box-shadow: 0 4px 15px rgba(48, 43, 99, 0.2);"
        "            background: #ffffff;"
        "        }"
        "        .domain-label {"
        "            font-weight: 700;"
        "            font-size: 1.1em;"
        "            color: #1a1a2e;"
        "            min-width: 140px;"
        "        }"
        "        .domain-desc {"
        "            color: #555;"
        "            font-size: 0.95em;"
        "            flex: 1;"
        "            padding: 0 15px;"
        "        }"
        "        .domain-os {"
        "            font-weight: 700;"
        "            font-size: 1.2em;"
        "            color: #302b63;"
        "            background: #e8e6f0;"
        "            padding: 6px 18px;"
        "            border-radius: 30px;"
        "            white-space: nowrap;"
        "            letter-spacing: 0.5px;"
        "        }"
        "        .domain-os.windows { color: #0078d4; background: #e3f0ff; }"
        "        .domain-os.android { color: #3ddc84; background: #e6f9ed; }"
        "        .domain-os.linux { color: #f48024; background: #fff4e6; }"
        "        .domain-os.kali { color: #557c94; background: #eaf0f5; }"
        "        .domain-os.rtos { color: #e74c3c; background: #fde8e6; }"
        "        .domain-os.embedded { color: #2ecc71; background: #e8f8ef; }"
        "        .domain-os.dos { color: #7f8c8d; background: #ecf0f1; }"
        "        .footer {"
        "            text-align: center;"
        "            margin-top: 25px;"
        "            color: #999;"
        "            font-size: 0.85em;"
        "            border-top: 1px solid #ddd;"
        "            padding-top: 20px;"
        "        }"
        "        .footer span { color: #302b63; font-weight: 600; }"
        "        @media (max-width: 650px) {"
        "            .domain-card { flex-wrap: wrap; }"
        "            .domain-desc { padding: 8px 0; flex-basis: 100%; }"
        "            .domain-os { margin-left: auto; }"
        "        }"
        "    </style>"
        "</head>"
        "<body>"
        "    <div class='container'>"
        "        <h1>🖥️ Operating Systems by Domain</h1>"
        ""
        "        <div class='domain-card'>"
        "            <span class='domain-label'>Desktop</span>"
        "            <span class='domain-desc'>Personal computers & laptops</span>"
        "            <span class='domain-os windows'>WINDOWS</span>"
        "        </div>"
        ""
        "        <div class='domain-card'>"
        "            <span class='domain-label'>Mobile</span>"
        "            <span class='domain-desc'>Smartphones, tablets & mobile devices</span>"
        "            <span class='domain-os android'>ANDROID</span>"
        "        </div>"
        ""
        "        <div class='domain-card'>"
        "            <span class='domain-label'>Server</span>"
        "            <span class='domain-desc'>Servers, cloud computing & enterprise applications</span>"
        "            <span class='domain-os linux'>LINUX</span>"
        "        </div>"
        ""
        "        <div class='domain-card'>"
        "            <span class='domain-label'>Cybersecurity</span>"
        "            <span class='domain-desc'>Ethical hacking, penetration testing & security analysis</span>"
        "            <span class='domain-os kali'>KALI LINUX</span>"
        "        </div>"
        ""
        "        <div class='domain-card'>"
        "            <span class='domain-label'>RTOS</span>"
        "            <span class='domain-desc'>Real-time systems requiring immediate response</span>"
        "            <span class='domain-os rtos'>RTOS<br><small>FREERTOS</small></span>"
        "        </div>"
        ""
        "        <div class='domain-card'>"
        "            <span class='domain-label'>Embedded</span>"
        "            <span class='domain-desc'>Dedicated devices like routers, TVs & ATMs</span>"
        "            <span class='domain-os embedded'>EMBEDDED LINUX</span>"
        "        </div>"
        ""
        "        <div class='domain-card'>"
        "            <span class='domain-label'>Legacy</span>"
        "            <span class='domain-desc'>Older computer operating systems</span>"
        "            <span class='domain-os dos'>MS-DOS</span>"
        "        </div>"
        ""
        "        <div class='footer'>"
        "            <span>/nameforge</span> &bull; Built with C & fac.io"
        "        </div>"
        "    </div>"
        "</body>"
        "</html>";

    // Kirim response HTTP
    http_set_body(response, html, strlen(html));
    http_set_content_type(response, "text/html");
    http_send_response(response, 200, NULL, 0);
}

int main() {
    // Inisialisasi server
    http_listen("3000", NULL, .on_request = on_request);
    printf("✅ Server C berjalan di: http://localhost:3000\n");
    printf("   Tekan Ctrl+C untuk menghentikan.\n");

    // Jalankan event loop
    fio_run();
    return 0;
}
